### ISSUE TITLE
Use different resolutions for storing and streaming

### ISSUE THREAD

**Issue by martelli** [igarape/copcast-android#155]
Currently the same resolution is used for video recording and streaming.
We must be able to record video at high quality and stream in low quality.

**Comment by brunosiqueira** [comment]
Duplicated from #154

**Comment by brunosiqueira** [comment]
Got an error when starting mission with this configuration:

```
            buildConfigField "int", "RECORDING_QUALITY", "android.media.CamcorderProfile.QUALITY_LOW"
            buildConfigField "int", "RECORDING_BITRATE", "300000"
            buildConfigField "int", "RECORDING_FRAMERATE", "15"
            buildConfigField "int", "STREAMING_QUALITY", "android.media.CamcorderProfile.QUALITY_HIGH"
            buildConfigField "int", "STREAMING_BITRATE", "200000"
            buildConfigField "int", "STREAMING_FRAMERATE", "5"

```
```
06-10 15:55:09.168 26659-26659/br.org.igarape.copcast E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: br.org.igarape.copcast, PID: 26659
                                                                        java.lang.ArrayIndexOutOfBoundsException: length=9600; index=9600
                                                                            at org.igarape.webrecorder.VideoProducer.shrink(VideoProducer.java:251)
                                                                            at org.igarape.webrecorder.VideoProducer.liveConsumeFrame(VideoProducer.java:176)
                                                                            at org.igarape.webrecorder.VideoProducer.onPreviewFrame(VideoProducer.java:143)
                                                                            at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1146)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

=======================
Got another error stopping the mission with this configuration:

         ```
   buildConfigField "int", "RECORDING_QUALITY", "android.media.CamcorderProfile.QUALITY_HIGH"
            buildConfigField "int", "RECORDING_BITRATE", "300000"
            buildConfigField "int", "RECORDING_FRAMERATE", "15"
            buildConfigField "int", "STREAMING_QUALITY", "android.media.CamcorderProfile.QUALITY_LOW"
            buildConfigField "int", "STREAMING_BITRATE", "200000"
            buildConfigField "int", "STREAMING_FRAMERATE", "5"
```

```
06-10 16:07:50.284 31092-31092/br.org.igarape.copcast E/org.igarape.webrecorder.VideoProducer: Params:720x1280 / 240x320
06-10 16:07:50.284 31092-31092/br.org.igarape.copcast D/AndroidRuntime: Shutting down VM
06-10 16:07:50.292 31092-31092/br.org.igarape.copcast E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: br.org.igarape.copcast, PID: 31092
                                                                        java.lang.IllegalStateException
                                                                            at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
                                                                            at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:990)
                                                                            at org.igarape.webrecorder.VideoProducer.liveConsumeFrame(VideoProducer.java:181)
                                                                            at org.igarape.webrecorder.VideoProducer.onPreviewFrame(VideoProducer.java:143)
                                                                            at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1146)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```
