### ISSUE TITLE
Intermitent error when recovering from a crash

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#162]
05-25 06:21:47.587 6433-6993/br.org.igarape.copcast E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                      Process: br.org.igarape.copcast, PID: 6433
                                                                      java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.igarape.copcast.utils.StateManager.setState(org.igarape.copcast.state.State, org.json.JSONObject)' on a null object reference
                                                                          at org.igarape.copcast.utils.StateManager.setStateOrDie(StateManager.java:90)
                                                                          at org.igarape.copcast.utils.StateManager.setStateOrDie(StateManager.java:85)
                                                                          at org.igarape.copcast.views.LoginActivity$2$1.success(LoginActivity.java:150)
                                                                          at org.igarape.copcast.utils.NetworkUtils$1.doInBackground(NetworkUtils.java:237)
                                                                          at org.igarape.copcast.utils.NetworkUtils$1.doInBackground(NetworkUtils.java:154)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                          at java.lang.Thread.run(Thread.java:818) 
05-25 06:21:49.179 6433-6993/br.org.igarape.copcast I/Process: Sending signal. PID: 6433 SIG: 9
05-25 06:22:02.409 7275-7275/br.org.igarape.copcast I/GMPM: App measurement is starting up, version: 8487

**Comment by martelli** [comment]
I've been using the app and I do not experience any issues after a crash recover.
