### ISSUE TITLE
Force to finalize all services and restart app when closing the app

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#172]
The Record Service is not being finalized when closing the app, only when stoping the mission. This error shows app when restarting the app/mission:

```
 Caused by: java.lang.RuntimeException: Fail to connect to camera service
                                                                          at android.hardware.Camera.<init>(Camera.java:528)
                                                                          at android.hardware.Camera.open(Camera.java:384)
                                                                          at org.igarape.webrecorder.VideoProducer.<init>(VideoProducer.java:38)
                                                                          at org.igarape.webrecorder.WebRecorder.prepare(WebRecorder.java:189)
                                                                          at org.igarape.copcast.service.VideoRecorderService.prepareMediaEncoder(VideoRecorderService.java:224)
                                                                          at org.igarape.copcast.service.VideoRecorderService.access$200(VideoRecorderService.java:44)
                                                                          at org.igarape.copcast.service.VideoRecorderService$MediaPrepareTask.doInBackground(VideoRecorderService.java:297)
                                                                          at org.igarape.copcast.service.VideoRecorderService$MediaPrepareTask.doInBackground(VideoRecorderService.java:293)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                          at java.lang.Thread.run(Thread.java:818) 
```

**Comment by brunosiqueira** [comment]
@ebadran to test it:
Finalize a mission in the following two ways:
1 - click the button stop mission
2 - stop the app through the app manager while the mission is ongoing.
Result: both videos should be played successfully in the playback screen

ps: the dev server is enabled to show the playback screen
