### ISSUE TITLE
Changing to uploading state

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#182]
"I got an error message: ""Transition from [RECORDING] to [UPLOADING] is forbidden. When I dissmiss the message, the app restarts to the welcome screen and the mission is disabled.
The upload button must be disabled while mission is active.
(see the screenshot)"

![captura de tela 2016-07-05 as 14 42 44](https://cloud.githubusercontent.com/assets/28031/16586683/06367bc2-42bf-11e6-9015-3a54fc26daae.png)

**Comment by martelli** [comment]
The error is actually that the upload button must not be available during a mission, right?

**Comment by brunosiqueira** [comment]
I got this stacktrace for the error when stopping a mission

```
07-11 18:27:45.633 14482-14482/br.org.igarape.copcast D/org.igarape.copcast.views.MainActivity: destroyed
07-11 18:27:45.658 14482-14482/br.org.igarape.copcast E/ActivityThread: Activity org.igarape.copcast.views.MainActivity has leaked ServiceConnection org.igarape.copcast.views.MainActivity$1@ded10b9 that was originally bound here
                                                                        android.app.ServiceConnectionLeaked: Activity org.igarape.copcast.views.MainActivity has leaked ServiceConnection org.igarape.copcast.views.MainActivity$1@ded10b9 that was originally bound here
                                                                            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1077)
                                                                            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:971)
                                                                            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1913)
                                                                            at android.app.ContextImpl.bindService(ContextImpl.java:1896)
                                                                            at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
                                                                            at org.igarape.copcast.views.MainActivity$7.startMission(MainActivity.java:373)
                                                                            at org.igarape.copcast.views.MainActivity$7.onClick(MainActivity.java:352)
                                                                            at android.view.View.performClick(View.java:4785)
                                                                            at android.view.View$PerformClick.run(View.java:19884)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

```

**Comment by brunosiqueira** [comment]
Was able to reproduce "trying to switch to the same state [RECORDING]"
1 - start mission
2 - request livestream
3 - pause mission
4 - resume mission
5 - end mission
RESULT: shows the error message.

**Comment by brunosiqueira** [comment]
New situation:

![screenshot_2016-07-12-17-32-56](https://cloud.githubusercontent.com/assets/28031/16775276/ca140bac-4857-11e6-8947-de62eaa1050d.png)
