### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by dborkan** [igarape/copcast-android#189]
Seen with webrecorder branch on July 6, 2016.  I had been using the Android app for a while (including uploading videos and realtime streaming), then I switched to other apps on my phone.  When I returned to the app and clicked "Start Mission" the app crashed.  From the Android Monitor I see the error was:
```
                                                                    --------- beginning of crash
07-06 11:59:18.420 4471-4471/br.org.igarape.copcast E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: br.org.igarape.copcast, PID: 4471
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.igarape.copcast.utils.StateManager.isState(org.igarape.copcast.state.State)' on a null object reference
                                                                          at org.igarape.copcast.views.MainActivity$7.onClick(MainActivity.java:331)
                                                                          at android.view.View.performClick(View.java:5204)
                                                                          at android.view.View$PerformClick.run(View.java:21155)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dborkan** [comment]
I believe this occurred when I refreshed the admin console

**Comment by brunosiqueira** [comment]
I am guessing there's an abnormal scenario where the app restarts, but not through the Splash Screen.
The state manager is initialized at SplashScreenActivity#onResume() via Globals.initStateManager(this);
Should we check if all the information is present and, if not redirect to the SplashScreen?

**Comment by dborkan** [comment]
I think that's correct.  I'm not totally sure why this happens yet but I was able to replicate this morning - I had been using CopCast yesterday but switched away from it and used a variety of other apps since, then when I switched back to it and clicked "Start Mission" I got the same error.

Here's slightly longer logs from when I got the error (note you don't see the "SplashScreenActivity" logs that normally appear):
```
07-07 08:43:58.301 32180-32180/br.org.igarape.copcast W/System: ClassLoader referenced unknown path: /data/app/br.org.igarape.copcast-1/lib/arm64
07-07 08:43:58.517 32180-32180/br.org.igarape.copcast D/org.igarape.copcast.receiver.BatteryReceiver: broadcastBatteryStatus msg=[org.igarape.copcast.POWER_PLUGGED]
07-07 08:44:06.054 32526-32526/br.org.igarape.copcast W/System: ClassLoader referenced unknown path: /data/app/br.org.igarape.copcast-1/lib/arm64
07-07 08:44:06.464 32526-32526/br.org.igarape.copcast W/System: ClassLoader referenced unknown path: /data/app/br.org.igarape.copcast-1/lib/arm64
07-07 08:44:06.825 32526-32564/br.org.igarape.copcast D/org.igarape.copcast.utils.NetworkUtils: https://dev-api.mycopcast.com/users/me
07-07 08:44:06.883 32526-32526/br.org.igarape.copcast D/org.igarape.copcast.utils.FileUtils:  file path name /data/user/0/br.org.igarape.copcast/files/smartpolicing/
07-07 08:44:07.009 32526-32569/br.org.igarape.copcast D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-07 08:44:07.195 32526-32569/br.org.igarape.copcast I/Adreno: QUALCOMM build                   : 63c06b2, I8366cd0437
                                                                Build Date                       : 12/06/15
                                                                OpenGL ES Shader Compiler Version: XE031.05.13.02
                                                                Local Branch                     : mybranch17112971
                                                                Remote Branch                    : quic/LA.BF64.1.2.9_v2
                                                                Remote Branch                    : NONE
                                                                Reconstruct Branch               : NOTHING
07-07 08:44:07.207 32526-32569/br.org.igarape.copcast I/OpenGLRenderer: Initialized EGL, version 1.4
07-07 08:44:11.887 32526-32526/br.org.igarape.copcast D/AndroidRuntime: Shutting down VM
                                                                        
                                                                        
                                                                        --------- beginning of crash
07-07 08:44:11.915 32526-32526/br.org.igarape.copcast E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: br.org.igarape.copcast, PID: 32526
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.igarape.copcast.utils.StateManager.isState(org.igarape.copcast.state.State)' on a null object reference
[same stack as before]
```

**Comment by brunosiqueira** [comment]
@dborkan I was able to reproduce it very easily by opening a lot of applications in my device and using them for a little more than one minute. I just commited the correction. Could you retest it and  confirm if it is working for you now?

**Comment by dborkan** [comment]
I'm not able to replicate that consistently yet, but I will test out the
new app and let you know if I see any more crashes.  Thanks
