### ISSUE TITLE
Crash initializing codec

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#195]
```
Stack:
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: Failed to initialize OMX.qcom.video.encoder.avc, error 0xfffffffe
at android.media.MediaCodec.native_setup(Native Method)
at android.media.MediaCodec.<init>(MediaCodec.java:486)
at android.media.MediaCodec.createByCodecName(MediaCodec.java:470)
at org.igarape.webrecorder.VideoCodec.<init>(VideoCodec.java:22)
at org.igarape.webrecorder.WebRecorder._prepare(WebRecorder.java:239)
at org.igarape.webrecorder.WebRecorder.prepare(WebRecorder.java:213)
at org.igarape.copcast.service.VideoRecorderService.prepareMediaEncoder(VideoRecorderService.java:224)
at org.igarape.copcast.service.VideoRecorderService.access$200(VideoRecorderService.java:43)
at org.igarape.copcast.service.VideoRecorderService$MediaPrepareTask.doInBackground(VideoRecorderService.java:319)
at org.igarape.copcast.service.VideoRecorderService$MediaPrepareTask.doInBackground(VideoRecorderService.java:315)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more

**** End of current Report ***
```

**Comment by brunosiqueira** [comment]
closing the issue since we did not receive any other similar error for the past 2 months
