### ISSUE TITLE
Copcast crashed (Stef's phone)

### ISSUE THREAD

**Issue by brunosiqueira** [igarape/copcast-android#214]
```
Information

Error Report collected on : Tue Sep 20 12:02:41 SAST 2016

Informations :
Locale: en_ZA
Version: 2.1.4
Package: br.org.igarape.copcast
Phone Model: SM-A310F
Android Version: 5.1.1
Board: universal7580
Brand: samsung
Device: a3xelte
Host: SWDD6315
ID: LMY47X
Model: SM-A310F
Product: a3xeltexx
Type: user
Total Internal memory: 11679260672
Available Internal memory: 5094211584

Stack:
java.lang.IllegalStateException: must call close()
at okhttp3.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:108)
at io.socket.engineio.client.transports.WebSocket$3.call(WebSocket.java:173)
at io.socket.engineio.parser.Parser.encodePacket(Parser.java:63)
at io.socket.engineio.parser.Parser.encodePacket(Parser.java:42)
at io.socket.engineio.client.transports.WebSocket.write(WebSocket.java:168)
at io.socket.engineio.client.Transport$3.run(Transport.java:101)
at io.socket.thread.EventThread.exec(EventThread.java:50)
at io.socket.engineio.client.Transport.send(Transport.java:96)
at io.socket.engineio.client.Socket.flush(Socket.java:608)
at io.socket.engineio.client.Socket.onDrain(Socket.java:599)
at io.socket.engineio.client.Socket.access$1000(Socket.java:30)
at io.socket.engineio.client.Socket$6.call(Socket.java:294)
at io.socket.emitter.Emitter.emit(Emitter.java:117)
at io.socket.engineio.client.transports.WebSocket$2$1.run(WebSocket.java:160)
at io.socket.thread.EventThread$2.run(EventThread.java:75)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by brunosiqueira** [comment]
Apparently, updating the lib solves the problem:

https://github.com/socketio/socket.io-client-java/issues/313
